version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: root-db
    ports:
      - 27017:27017
    volumes:
      - ./testdata/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:rw
  